# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Speakeasy AI Control Plane CLI"
  homepage "https://ai.speakeasy.com"
  version "0.18.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/gram/releases/download/cli@0.18.0/speakeasy_darwin_amd64.zip"
      sha256 "9bb08390203f8751ed5449329f57db7e81648bbab71f8c05255645cbaf20152a"

      define_method(:install) do
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/gram/releases/download/cli@0.18.0/speakeasy_darwin_arm64.zip"
      sha256 "be7868baf6cec9051ec550e896ced457a4ef2f3e0a4879bfb45c668d4c70fb51"

      define_method(:install) do
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/cli@0.18.0/speakeasy_linux_amd64.zip"
      sha256 "4a57a44ed9a0497b4d4747b92ffdd37ff2a1f9c77272b23887ed457df575fe35"
      define_method(:install) do
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/cli@0.18.0/speakeasy_linux_arm64.zip"
      sha256 "c4646c0441b1a74f6a2d3519148d64b3184e21841530ad1b02f72a236afa20fa"
      define_method(:install) do
        bin.install "speakeasy"
      end
    end
  end

  conflicts_with "speakeasy"

  test do
    system "#{bin}/speakeasy --version"
  end
end
