# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gram < Formula
  desc "The Gram CLI for interacting with the Gram Platform"
  homepage "https://app.getgram.ai"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/gram/releases/download/0.6.0/gram_darwin_amd64.zip"
      sha256 "86c4e1013944f030a0e39f33ecb472645ccf80ed26621f75faeba1a5a1fbe755"

      def install
        bin.install "gram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/gram/releases/download/0.6.0/gram_darwin_arm64.zip"
      sha256 "94a6cd052f4f02957c8e9fc0e39b688a3d8245e17f9154b5ea49771824161482"

      def install
        bin.install "gram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/0.6.0/gram_linux_amd64.zip"
      sha256 "946a8f08435d7d5df62a33a3f455dc71522a8ac3ae113c945ce3a705691bd987"
      def install
        bin.install "gram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/0.6.0/gram_linux_arm64.zip"
      sha256 "053d0acde6740ac1387c3a38d2ddecccb9b4134f0a4a56a1b5c8fd4234cff29f"
      def install
        bin.install "gram"
      end
    end
  end

  test do
    system "#{bin}/gram --version"
  end
end
