# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gram < Formula
  desc "The Gram CLI for interacting with the Gram Platform"
  homepage "https://app.getgram.ai"
  version "0.1.8-rc.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/gram/releases/download/0.1.8-rc.0/gram_darwin_amd64.zip"
      sha256 "674015144b22528aefe0d05172a1627b592caa253f88a040311ad277c9fd83ba"

      def install
        bin.install "gram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/gram/releases/download/0.1.8-rc.0/gram_darwin_arm64.zip"
      sha256 "14be09fa40928121ac60a575360c87a806ae51a786e781bc4d4ac62ecf2d8193"

      def install
        bin.install "gram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/0.1.8-rc.0/gram_linux_amd64.zip"
      sha256 "12cdcbec957d792f77acc1a602c68ea3f01df6802b46fff06a603a3ddf36c0d0"
      def install
        bin.install "gram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/0.1.8-rc.0/gram_linux_arm64.zip"
      sha256 "78802c99c6e95220f42e42176d8b7c50eddc0c61595d2c87af603a16ad1946f5"
      def install
        bin.install "gram"
      end
    end
  end

  test do
    system "#{bin}/gram --version"
  end
end
