# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12605 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.260.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.5/speakeasy_darwin_amd64.zip"
      sha256 "714e7e5ace6a1291b355b7a8d39f026f9fd7340542f5000143ae5a07efab2295"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.5/speakeasy_darwin_arm64.zip"
      sha256 "8b31e4791a5b7361b79f191b65a35c07251580685dee404e94b00d6562aa787e"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.5/speakeasy_linux_amd64.zip"
      sha256 "928828f493f7a00bc6b47a25dde873cbc3f894ecc84ed419f17df3ed9f79c759"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.5/speakeasy_linux_arm64.zip"
      sha256 "fddc80c4052a4f47b61f6c02273061022040d7097b6cecbb91161fc64a7aee43"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
