# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1379 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.37.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.37.9/speakeasy_darwin_arm64.tar.gz"
      sha256 "ed04bd0ece5e8f123e63c2cd0a16b37439c4c40747d62b4adfac4a05ed0ea796"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.37.9/speakeasy_darwin_amd64.tar.gz"
      sha256 "003f5534a087cdf3b95bdb90a89664d50d058d09951999da1eb8c8ac9dede79f"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.37.9/speakeasy_linux_amd64.tar.gz"
      sha256 "18984e4490f09518f72e0ffe349d4e5c70f1ed48f24f74779c618beeaf38d0e8"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.37.9/speakeasy_linux_arm64.tar.gz"
      sha256 "9d1222beb3b15b7da5f04b1bf820570a29687296c4afdd50ed34981f72259bce"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
