# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13620 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.362.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.362.0/speakeasy_darwin_amd64.zip"
      sha256 "bf6e1eebd720df82cc399a1dba3126287448733b068a5a9551b4843c754a5bae"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.362.0/speakeasy_darwin_arm64.zip"
      sha256 "605ed1c643fdf70e6ab9b4b0c46a0efdcb4cbce4ef34eee9c3e25f7893fccf1d"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.362.0/speakeasy_linux_amd64.zip"
        sha256 "a1daa554852af528c6836d378eb575bd2f38bfca84caa23c2f15f022e49f1fbe"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.362.0/speakeasy_linux_arm64.zip"
        sha256 "d6ae98268142759067ffd20e64dc6dfef8fa7e06df963bd6334ba45c0d2b2cc4"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
