# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14542 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.454.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.454.2/speakeasy_darwin_amd64.zip"
      sha256 "08dfd5eccc09e0d37cdf9fd3a699f99dcf0f670ce47a35fc7f6b9fc64c5c5c4f"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.454.2/speakeasy_darwin_arm64.zip"
      sha256 "d941b6c31c247b185820f269ab98a4827bda0bf9042ccd774cb8327e5bb3690c"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.454.2/speakeasy_linux_amd64.zip"
        sha256 "42a61849d56ea518ed54bbb7893cf4b88c00d3271dba83b1afc083066a752bb3"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.454.2/speakeasy_linux_arm64.zip"
        sha256 "575dbbae99d4f38c67da7f860439a51222198bfe489385e1b3bedf7939595d6b"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
