# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12323 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.232.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.232.3/speakeasy_darwin_arm64.zip"
      sha256 "f2fe8ff0ab34f752a19d909cadde9f6d1371b999110fb6c438c755b90e60e10b"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.232.3/speakeasy_darwin_amd64.zip"
      sha256 "278e292f6ffe6a0b646937c5338dfb281032479d5b2ed7df1caed9173e504887"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.232.3/speakeasy_linux_arm64.zip"
      sha256 "8b3be1fe16e7d14f13e4da9ed5dc9eeff5a905cb92f946fdeb8ab4b03d91afa5"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.232.3/speakeasy_linux_amd64.zip"
      sha256 "5420c9454f1965e255371779eeb5af9057f59069b1303c075636f65e1057e6f3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
