# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13560 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.356.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.356.0/speakeasy_darwin_amd64.zip"
      sha256 "2516f993bcdd04f3bec553594aa0bb92759513a4fe3950dc5a5431056751d512"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.356.0/speakeasy_darwin_arm64.zip"
      sha256 "8fb9523df6889ad5cf9c831e942274ba86efc2ce9d8ddc1d694852e1a454daf6"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.356.0/speakeasy_linux_amd64.zip"
        sha256 "ae13734cf5a5148091398a2e02c53776ef38dea0394e128bae8889c61d6810f7"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.356.0/speakeasy_linux_arm64.zip"
        sha256 "ccdb76f03b47b8fbfa7f1bc5b4368d42e31233b190ea92a41310e492325b83ac"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
