# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15401 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.540.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.540.1/speakeasy_darwin_amd64.zip"
      sha256 "32a2dc9904a9d5084a5642c239938e458e364ede54969adcb26c07d4a3806089"

      def install
        bin.install "speakeasy"
        bash_completion.install "completions/speakeasy.bash" => "speakeasy"
        zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
        fish_completion.install "completions/speakeasy.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.540.1/speakeasy_darwin_arm64.zip"
      sha256 "5785ff84c79b157bb5065764ed562f64b0d18c6671b19581ad5396adb731b439"

      def install
        bin.install "speakeasy"
        bash_completion.install "completions/speakeasy.bash" => "speakeasy"
        zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
        fish_completion.install "completions/speakeasy.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.540.1/speakeasy_linux_amd64.zip"
        sha256 "307f369d45bbd89609d0816a007fea8257189666dd1ee9baac154e98997d8b9c"

        def install
          bin.install "speakeasy"
          bash_completion.install "completions/speakeasy.bash" => "speakeasy"
          zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
          fish_completion.install "completions/speakeasy.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.540.1/speakeasy_linux_arm64.zip"
        sha256 "81cf41b5d8de16ffce091dbafe6fcd9e271e412861c919ef9fd35c56a326c408"

        def install
          bin.install "speakeasy"
          bash_completion.install "completions/speakeasy.bash" => "speakeasy"
          zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
          fish_completion.install "completions/speakeasy.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
