# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15192 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.519.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.519.2/speakeasy_darwin_amd64.zip"
      sha256 "d623ea754c47fa226ee53d7d00eeb9e77cb286527782ce54b9a7a50670b72dfb"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.519.2/speakeasy_darwin_arm64.zip"
      sha256 "c3b92dcfdcfa80aff02dfc21deea96e407fe81e8ed044e84c46737d34182ff33"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.519.2/speakeasy_linux_amd64.zip"
        sha256 "4f6e9ee628267c461a9c421a77cf3704722fd5d807d01794ab23a7d43f26eccc"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.519.2/speakeasy_linux_arm64.zip"
        sha256 "768c8b8d702a6cd8a104ef9deaebd7d1bba04a0ccabee8be767663e492e0f864"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
