# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15001 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.500.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.500.1/speakeasy_darwin_amd64.zip"
      sha256 "fdf9d31b32bfe299ebeadccfcbcb81a86bfeabca8e3d190918349fdd2a9df8c8"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.500.1/speakeasy_darwin_arm64.zip"
      sha256 "6776d2204dab513415e638fd5fa10a08191fda1a1c64d71180812ebc76a4aab1"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.500.1/speakeasy_linux_amd64.zip"
        sha256 "3d0957c446a2c6ed84d289828c1fdb6b5f89bb0ac7c9f0484588501781353b20"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.500.1/speakeasy_linux_arm64.zip"
        sha256 "cc462ffac5021b7e6f354faa3bbd0629c14bb5b94ab04398aeb53f01b1c815a9"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
