# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13490 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.349.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.349.0/speakeasy_darwin_amd64.zip"
      sha256 "87c4efa7f9946ada5fab0df2e95f99d99150200990d5d9bd6d5ab3d0398f6e67"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.349.0/speakeasy_darwin_arm64.zip"
      sha256 "9f5278587ff353fd88945b9e306130233cf377502904ec80fe7761a21585eab2"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.349.0/speakeasy_linux_amd64.zip"
        sha256 "4ee129d76e09fee699e780d8ae712be09f2f1b193ff570439a215dd99c4bbadf"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.349.0/speakeasy_linux_arm64.zip"
        sha256 "6218520f3fc3cd7b9ee3eb9199440027b3a62d299c1093d0fcb6a0d1df67d98d"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
