# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11332 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.133.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.133.2/speakeasy_darwin_amd64.zip"
      sha256 "5807df992beebf2abce5ab67de2076a3c9dbfbd8b975628f3a1766aae02f791c"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.133.2/speakeasy_darwin_arm64.zip"
      sha256 "8af5a8a01b747ff92286a7a05720430102a8c71029e85094797bbf15d49b3c9c"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.133.2/speakeasy_linux_arm64.zip"
      sha256 "695d629608d52443a4dddc7b028eaf2632952076dca15ae7e7168e4f435160bb"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.133.2/speakeasy_linux_amd64.zip"
      sha256 "811ac8256bbffb34cc7acf08109cb38234c67a5de367218022676e7d101f1572"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
