# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1782 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.78.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.2/speakeasy_darwin_amd64.zip"
      sha256 "8e0715f43876cba306442d914a5364f1f4d67f80bfae91060b3232f06687eeed"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.2/speakeasy_darwin_arm64.zip"
      sha256 "fafffbc823842b2c9ad708db29213d312bdd4e6dfc0d4b352ad08aded01461e4"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.2/speakeasy_linux_arm64.zip"
      sha256 "9d56bef0357abb2e84c1842e60321da32873fef79af42ac4004d27bb27c67c3a"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.2/speakeasy_linux_amd64.zip"
      sha256 "20dbf62d3e4f0b08cc24efbdb8d97820c0751dbc9032fb4c2227f57089780a9f"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
