# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14590 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.459.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.459.0/speakeasy_darwin_amd64.zip"
      sha256 "3aa0699ee5bc4445a055fa27dc4c9689f9721dcef2ffdf7d398e3146e8a1fa0c"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.459.0/speakeasy_darwin_arm64.zip"
      sha256 "03448dece6b513255e5c0b9fb6faae42afdcfa2e6296fe56233c4bf857fc8076"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.459.0/speakeasy_linux_amd64.zip"
        sha256 "64acb73b1517ab2ed54610a94cfe5c251ea4dc359eae083f1898c8d15dc727fc"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.459.0/speakeasy_linux_arm64.zip"
        sha256 "5813ac835d5b1bf6266adbfe8df64de5336eb58a396f988933bee5013b8bff4b"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
