# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1780 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.78.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.0/speakeasy_darwin_amd64.zip"
      sha256 "bce3bc441a37334bffebc8bed1726aafe26fceb10038bc7916edf390db6f0873"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.0/speakeasy_darwin_arm64.zip"
      sha256 "0ec7d17439525e4e49c6e88d027cfadb4640937d4a2142f5adafa6fd4fafc2af"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.0/speakeasy_linux_arm64.zip"
      sha256 "cde66e674c645f2e79f459dcab256e1066cbe06b502af5e15a106a57dcb7fd2e"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.0/speakeasy_linux_amd64.zip"
      sha256 "0bdea8db3c5cce6ce228e00ec8b59d4c1e7cee6bfac00be5b3e700057fbbefcc"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
