# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14650 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.465.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.465.0/speakeasy_darwin_amd64.zip"
      sha256 "dce727d0edf2c9373e13ac8725d4c2ccb5da9c31f28cf234177d2c692da7e993"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.465.0/speakeasy_darwin_arm64.zip"
      sha256 "931290aebc72de7eb0c3beb80eb7edf8499dd984b85dfa7d5cf0374441800a00"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.465.0/speakeasy_linux_amd64.zip"
        sha256 "e894086ecc938f098781ed8d3aa19601c62ee507a9bd8239f1cf9390d736299e"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.465.0/speakeasy_linux_arm64.zip"
        sha256 "5f5ad4b2847315a5dbf06f04217dae9d8e73c2b0f27e7e97495d17a74b09606b"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
