# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11500 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.150.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.150.0/speakeasy_darwin_arm64.zip"
      sha256 "5fcf049ecdbe1e48f04fda5c1478be1b7950cb56350a05fb6c32ed71bdf4057a"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.150.0/speakeasy_darwin_amd64.zip"
      sha256 "e870c59110fa25ab2763179f7ef37f24b0e0c9f9d2ecf0a73541ababea474075"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.150.0/speakeasy_linux_amd64.zip"
      sha256 "4ce596b0751f43720ceebc2cef7a2841682fa25d334fce1aa6becc4d4310c917"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.150.0/speakeasy_linux_arm64.zip"
      sha256 "e2fffdeb1448bfa61da1cebd5205f59809f8a6723efb91cd26a5524b190fe907"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
