# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1601 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.60.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.60.1/speakeasy_darwin_amd64.zip"
      sha256 "dfe5dc1cdb53c61e89e8b3d114872ad114086e17953787a23bd9b7b9d736c53a"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.60.1/speakeasy_darwin_arm64.zip"
      sha256 "72b3837a1fd4958d9ad5fb2e883271628e9838123e70ebbafc9269489dbaf074"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.60.1/speakeasy_linux_amd64.zip"
      sha256 "0d33b197d586080f086c1c10e5156f9073462e8856ad567f69ba36ca52ed0cbc"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.60.1/speakeasy_linux_arm64.zip"
      sha256 "723b09839d5a96f63d682866f8b8ca77a18d6128df7a32745916e8c7a6c9f7a6"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
