# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14692 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.469.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.2/speakeasy_darwin_amd64.zip"
      sha256 "e1b7dfb8f1f1bd3c0690eb1b480520df1e2015b365276bc5fcb6380c0e85dd29"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.2/speakeasy_darwin_arm64.zip"
      sha256 "fbf3f208776e3d0b407c2a56bf94624cf0df05bc811cfa5722fa8470cc24bee6"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.2/speakeasy_linux_amd64.zip"
        sha256 "f38ae974fd756c6ff649a3d7a263cc3cf1f08a89969813c42ddd26cbae88fe5a"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.2/speakeasy_linux_arm64.zip"
        sha256 "841694718023e510646a8e9e274c92cb3dfad0acce4711290cb37a89ec694806"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
