# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14370 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.437.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.437.0/speakeasy_darwin_amd64.zip"
      sha256 "64fdc0a22f4e29b23afc3e35d43c84c773f4520e0244c0e3dafd39f59ce17468"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.437.0/speakeasy_darwin_arm64.zip"
      sha256 "541d310beddc29a97730aff29117e09b59ea4d2aedf074a2287e1389af0a5b06"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.437.0/speakeasy_linux_amd64.zip"
        sha256 "ea285f52e913de4bfaed750c4b1f88c631557f984b6f3b11834f280726d39b1e"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.437.0/speakeasy_linux_arm64.zip"
        sha256 "fbc1089c5cf27c9cd64747c0fb6e30f0b7a1df6e6317cb4f6a4c04c49d7debde"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
