# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT0213 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "0.21.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v0.21.3/speakeasy_0.21.3_Darwin_x86_64.tar.gz"
      sha256 "90e66e046cce1ef25284cac2ef357803738091737de155653257171c4f4285e2"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v0.21.3/speakeasy_0.21.3_Darwin_arm64.tar.gz"
      sha256 "5f7af131506c62e13a9cdb6ade68fb1bdd828d726a55d68d450876f2a45f1712"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v0.21.3/speakeasy_0.21.3_Linux_arm64.tar.gz"
      sha256 "0175e735f154cd4244993582386409b3f438505c516b15bcf5341ed104610eca"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v0.21.3/speakeasy_0.21.3_Linux_x86_64.tar.gz"
      sha256 "b921b18856c3babcb402eeb0ee78f27a6af9d5e25a3ca39c25354231e67aaa2d"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
