# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13001 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.300.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.300.1/speakeasy_darwin_amd64.zip"
      sha256 "7f470403add989fbc885e979efc1575ba6100207abf17dde32ea20201caa630b"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.300.1/speakeasy_darwin_arm64.zip"
      sha256 "e7857b3ec8e65d124f1c780e45fc7f95279e1ba3f816e5d82ceaeb4d71af0dfa"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.300.1/speakeasy_linux_amd64.zip"
        sha256 "aaa85d004f5a24080b044ed52cc9d612e07aeb426c930c4dd24c977e286c0bce"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.300.1/speakeasy_linux_arm64.zip"
        sha256 "d8fdc2a34a5f2d5f2eb8a3f3d970c4f8d5df7a172b7a3cf9af86b5c06d582dc3"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
