# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT146 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.4.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.4.6/speakeasy_1.4.6_Darwin_x86_64.tar.gz"
      sha256 "a1da82ba409460815c3de54496d2093bfa7600a05be3ed8cf26ce29d25d8c286"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.4.6/speakeasy_1.4.6_Darwin_arm64.tar.gz"
      sha256 "44891e83217c3bb502375058f09af214c8b94f66359c9a835da673343a61d0f8"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.4.6/speakeasy_1.4.6_Linux_arm64.tar.gz"
      sha256 "baafd0ffc2a126a8762e97386a0820fbb4899820ecff92506c4745c24921580f"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.4.6/speakeasy_1.4.6_Linux_x86_64.tar.gz"
      sha256 "9a2d4cf04012c9a185c8131fffbeaaaf942c1c7a1d945d56a089e3224e073578"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
