# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13291 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.329.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.329.1/speakeasy_darwin_amd64.zip"
      sha256 "78f7e8564c89e5f1c8b4c4131b389ed42c5faa7e41e4228f0c87d1067f902b06"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.329.1/speakeasy_darwin_arm64.zip"
      sha256 "d3ecb5686e165ea8fc87f4efabd4fff94e8998ed97c729e11a52060fbd90a6dd"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.329.1/speakeasy_linux_amd64.zip"
        sha256 "1a8ff8d8a2f8a363c964bb1b238d7aeddf856b895b32f51717a827af05959639"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.329.1/speakeasy_linux_arm64.zip"
        sha256 "ae5ae306763c90f79e3b4ca3552dfdf5081160edadc72b85bafcdd95fe134d10"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
