# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15040 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.504.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.504.0/speakeasy_darwin_amd64.zip"
      sha256 "d589a1a1be1ee3d99dfc7304d380b575409629f34a2f13acee4899c4b6ca5eab"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.504.0/speakeasy_darwin_arm64.zip"
      sha256 "c340d27da2bbfd977da46697e76654fc971d95e9e780b520331b9dc7b8549475"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.504.0/speakeasy_linux_amd64.zip"
        sha256 "020244956c35877e83a3f53dd7afa86f584d5edfe1dd43443d6e47359bb18339"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.504.0/speakeasy_linux_arm64.zip"
        sha256 "031568a87341b56ee6151aba0b1f24fd81360ce3e9dd6bbb27c174fdefbd3737"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
