# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11263 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.126.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.126.3/speakeasy_darwin_arm64.zip"
      sha256 "33a142596ed80c076211cb39491e5d85f2bc0fb731ddf297ff7a57840717f00f"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.126.3/speakeasy_darwin_amd64.zip"
      sha256 "f16a36d3ad055e7cac1a154a465c0f8f068634cd08213fd64345ff3ee4aece35"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.126.3/speakeasy_linux_arm64.zip"
      sha256 "09ab9707923b5252fcff4a5b9b03331eda5653e1c3875fb1b30e313792e1f10d"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.126.3/speakeasy_linux_amd64.zip"
      sha256 "ec0655c2ed97ffadcadddece52d59113c578c9903f4aaf040733a01c09a8f8c5"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
