# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1195 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.19.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.19.5/speakeasy_1.19.5_Darwin_x86_64.tar.gz"
      sha256 "bf6a0881d8572e97c6868b89e62b9fe2cc92a02c9095e3bd734a9f89dec6e1db"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.19.5/speakeasy_1.19.5_Darwin_arm64.tar.gz"
      sha256 "76e639358f523f4a6d668ae6e2e1331008c7f7484572f7c68d46b454eeb74205"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.19.5/speakeasy_1.19.5_Linux_arm64.tar.gz"
      sha256 "0be759257e6f041b8810142ac52a403f83468261183d4fd28357db7ed45d7fbf"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.19.5/speakeasy_1.19.5_Linux_x86_64.tar.gz"
      sha256 "13507abf149a843b2c26227009254bbe94714fe00cd9b4339813951873e130ea"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
