# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12900 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.290.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.290.0/speakeasy_darwin_amd64.zip"
      sha256 "710707c203a719d9f9b884bf489a1ceb19b8275498095517af2fa8eae68b5cd2"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.290.0/speakeasy_darwin_arm64.zip"
      sha256 "16369533e0971a75c3b213d390abe8489966baa034baf0ef8bed5f2bcf323f7c"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.290.0/speakeasy_linux_amd64.zip"
        sha256 "0b77bfe25675f42134b003f538ba87343ea225e3cbba89249f8cc72a5996810d"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.290.0/speakeasy_linux_arm64.zip"
        sha256 "add427c1b3cad028b51e4cb82cf02d7cd52e248529b37ff75594b6d77941b3b6"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
