# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14161 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.416.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.416.1/speakeasy_darwin_amd64.zip"
      sha256 "3d6d001f9ba5a268202e696c02ab1813171769c3345671cfa7dcbef39e3a000c"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.416.1/speakeasy_darwin_arm64.zip"
      sha256 "c0ec5b93522fcd31f58c51d0967e5a0647160ac7e772bc75cc49094ad3333313"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.416.1/speakeasy_linux_amd64.zip"
        sha256 "72910a5752056d94f56524d21ac5b4bce204170266f7b031a7e9f5caffbb5ffa"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.416.1/speakeasy_linux_arm64.zip"
        sha256 "b07232d99dbf541e15ff20f53af11c8d5fb1409c02d350aec3919c0d9f7ecec7"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
