# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13321 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.332.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.332.1/speakeasy_darwin_amd64.zip"
      sha256 "820fd011e7c04fb2e29de9c2f1d7e96b2b6fc600c3355d761ba0ae9680fd4258"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.332.1/speakeasy_darwin_arm64.zip"
      sha256 "caee2d9d3798eb0cef25706d584056900f2d9e38317ddf28f4be9f41b7badc82"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.332.1/speakeasy_linux_amd64.zip"
        sha256 "1c5bf3f6fb6dbe135281d439aa975919f7524bd4a8e26caa8f4c1fb30bcc9720"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.332.1/speakeasy_linux_arm64.zip"
        sha256 "27a166ff9775c220cfee1311699f6d7600072fa0a62b7396f121df0f15863638"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
