# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12990 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.299.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.299.0/speakeasy_darwin_amd64.zip"
      sha256 "5740e12bbc1739263485a65e34f4e716acdbb5064394e183e1efb3c91dd1e165"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.299.0/speakeasy_darwin_arm64.zip"
      sha256 "043f39bd82aa6d8dd21a2870a18b5bfeb6472c0cfc361728ff9dbb88fdf128b3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.299.0/speakeasy_linux_amd64.zip"
        sha256 "0630a9669cd9310efc9274bf42ad2151511c6b8ba4f7a55d9e383304def606d4"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.299.0/speakeasy_linux_arm64.zip"
        sha256 "cba74d554b81c3152cabde0f17988f6154980e65f6b1c746f11a1f7c68e04b2f"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
