# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1480 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.48.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.48.0/speakeasy_darwin_amd64.zip"
      sha256 "d6d4f18d252d1333cd590dd3ab7a1bfc8301241273681f368a289cdb14d6e1fd"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.48.0/speakeasy_darwin_arm64.zip"
      sha256 "fab890cc7ddc8f706d61a0e2d6b2de805208b5b0603c88ec154d5f28bef62a4b"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.48.0/speakeasy_linux_amd64.zip"
      sha256 "0402882c2e17a5ced3868146c2844e995139a1b1222eefcc9469e68a707fb68a"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.48.0/speakeasy_linux_arm64.zip"
      sha256 "0a42b049fc4026414b3c134738c6051789f0d13b547f87e70288aa1e2cd006b8"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
