# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12950 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.295.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.295.0/speakeasy_darwin_amd64.zip"
      sha256 "b87611d03b789ec13fca364e4ef7189171f472b61e5d5f7a280c0cf621ce3511"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.295.0/speakeasy_darwin_arm64.zip"
      sha256 "265a432d9bc39708251544b9d8d73986a6a4cf2499284f46e96398e780e17574"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.295.0/speakeasy_linux_amd64.zip"
        sha256 "ff44b6ea7abb73d3394f6727246e100d70c67e87adc66add4199a4076fff160a"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.295.0/speakeasy_linux_arm64.zip"
        sha256 "09637439b2813e6b1e85b3a943f7653919b96191c6a786b799ead8e4c145612c"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
