# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12602 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.260.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.2/speakeasy_darwin_amd64.zip"
      sha256 "f9c33bcbea17e2df18b72d8d4457d0183fa551ca55ec0dc1650a0cf523134fab"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.2/speakeasy_darwin_arm64.zip"
      sha256 "0cc38048d1c3f7464cb9e55c13f832f5a71d0085482ebc03a9c9512bbfcfcdd0"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.2/speakeasy_linux_amd64.zip"
      sha256 "fd437b1a6cc32ef1a6689c642ae38f8a35274c4fe520a59cb111df7a1205445b"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.260.2/speakeasy_linux_arm64.zip"
      sha256 "ac98800e27ecd66fcf6b4cc346d99c5cea8df2673052dead40a4a0388ce47e61"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
