# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13190 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.319.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.319.0/speakeasy_darwin_amd64.zip"
      sha256 "12bb442556ce2762f45141eb4537ab603a916bd1ba59ec05d06575ef7df01c21"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.319.0/speakeasy_darwin_arm64.zip"
      sha256 "3018dca96f4743a740179c49ff4d474454b8064c690de741032c9ea79fdfe613"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.319.0/speakeasy_linux_amd64.zip"
        sha256 "ceac6a908e06b0d4324548fbc61fa9f29c4c2c299521c474d122c621d671ef97"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.319.0/speakeasy_linux_arm64.zip"
        sha256 "d136b1609925dda331d1320aeaaa1f93bcc4765dcfa91585554e35c4b64dd2d3"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
