# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15300 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.530.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.530.0/speakeasy_darwin_amd64.zip"
      sha256 "528c237a52d3b33410dc460c31681a16e1c26082113ffc4e2f3e20f8ea8c40fd"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.530.0/speakeasy_darwin_arm64.zip"
      sha256 "09ea4d8fb42c455b4baa188806ff26966210a6f0bd490d7fcdbfeb43c65d1783"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.530.0/speakeasy_linux_amd64.zip"
        sha256 "b9cd9c9039214d70abe29c53c5d609c16e2d31cb934ad7e6521b260d1250f9f6"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.530.0/speakeasy_linux_arm64.zip"
        sha256 "e23dcb0a0f2babad23895412e5087f71792d43fd50cd9c1f691462d5f284df34"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
