# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14940 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.494.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.494.0/speakeasy_darwin_amd64.zip"
      sha256 "a301919ff3af78d6459995e14af7bcfe0838bf589c447441a2cb22907f11cc80"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.494.0/speakeasy_darwin_arm64.zip"
      sha256 "46636fa6ba6fccbd6bb8e10152dc0b18a71e6654d5aacc308fd0bfe45b4dad67"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.494.0/speakeasy_linux_amd64.zip"
        sha256 "2d34b5d963f4c4133b373c55f8d5c8ed9735a69b12d5e9c4f237b46856286183"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.494.0/speakeasy_linux_arm64.zip"
        sha256 "6810c354fc9d85c541c3b39fa77d8bd74a58852005fcc6732d70136c8d4a7344"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
