# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT146912 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.469.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.12/speakeasy_darwin_amd64.zip"
      sha256 "7ff45b17c92088c393a5576ca413c65e49a1d36a0067fca35c5a04dc0e945d78"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.12/speakeasy_darwin_arm64.zip"
      sha256 "e526f218cde59f1af9b614c4a94b9823e82f7a348876cdc05d9c0df098d26458"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.12/speakeasy_linux_amd64.zip"
        sha256 "537348d5ecd0d38804ab9c0020017091c421bebf7d270b52282fe338bc1d3935"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.469.12/speakeasy_linux_arm64.zip"
        sha256 "8a9878e89e39c05ac446a639256612029ea89845c1c18334f4352f55fe090240"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
