# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14631 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.463.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.463.1/speakeasy_darwin_amd64.zip"
      sha256 "92c15576d8914069bcbff38b1780706ad5c0515f11e9cadc420bafc8d08bd867"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.463.1/speakeasy_darwin_arm64.zip"
      sha256 "502f27e81a43154907c7fd8e1144951315d9de2766df1941a5d30312bb12a403"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.463.1/speakeasy_linux_amd64.zip"
        sha256 "677b85c535979d7678a981e93ccc4aac8c017d6178061eef0ee3db6a66df1033"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.463.1/speakeasy_linux_arm64.zip"
        sha256 "33f6b5e9709e13c09b9dbc1db7ee374c9f6311d42ab234add57ee9b801876a01"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
