# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13170 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.317.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.317.0/speakeasy_darwin_amd64.zip"
      sha256 "825cc1884fd46f639538b954f59920e6e160a66de4be7a4800b185cea08eb1dd"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.317.0/speakeasy_darwin_arm64.zip"
      sha256 "a5e33592bf7519ecfe9c32a55b4acc7d50ff051ae86085787b2a2e09f41bcd19"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.317.0/speakeasy_linux_amd64.zip"
        sha256 "b5a283a5588495ff00482447f3e16377225f94d7e54248fede7ed6938adaef7f"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.317.0/speakeasy_linux_arm64.zip"
        sha256 "dc1ff68886808c22faf5e52ea9dad47ec9b9063846ca6c8701817e444ea1aa75"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
