# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11010 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.101.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.101.0/speakeasy_darwin_amd64.zip"
      sha256 "1a3bfc7e6a7da802d8d17985d4f01c17513b4f9a4eea92b690dd0e4c7f1923d6"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.101.0/speakeasy_darwin_arm64.zip"
      sha256 "375eca0a88ca97a39abb701ba6ddf7d885802bd7c15d67f098e471485856e0a9"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.101.0/speakeasy_linux_amd64.zip"
      sha256 "8454976c6c1812bd44bce7c125c9e4b1cc9b27ff8150cec30cf29acb2e28039f"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.101.0/speakeasy_linux_arm64.zip"
      sha256 "2316748407d8e9788517581dfa75557ddf13f9f2a56aafeaffc54099db95b5f9"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
