# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyHooks < Formula
  desc "Speakeasy observability hooks for coding agents"
  homepage "https://app.getgram.ai"
  version "0.3.25"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.25/speakeasy-hooks_darwin_amd64.zip"
      sha256 "f3de18d5485b644bc824ad210176dd3d39d04ce34650cc88ca06b738e38280c8"

      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.25/speakeasy-hooks_darwin_arm64.zip"
      sha256 "10d12f399787f38d1127ab29a5fb7cb0956c802f9a677240638a738996027a6c"

      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.25/speakeasy-hooks_linux_amd64.zip"
      sha256 "b60f396a973e5586eaaf989b0946740dd7b6c1a577231ec6f113c40b9fca1d92"
      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.25/speakeasy-hooks_linux_arm64.zip"
      sha256 "1c6dd525ef344f8908152b4ad11ff5ffe700d4452405ee78a4fe18f411fc2ece"
      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
  end

  test do
    system "#{bin}/speakeasy-hooks --version"
  end
end
