# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14320 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.432.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.432.0/speakeasy_darwin_amd64.zip"
      sha256 "e655931ed9543db4af785746f93a983b2f8cd81d5b5231bff9e89fd73d2de098"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.432.0/speakeasy_darwin_arm64.zip"
      sha256 "019cf5d8ce8e0e6a4f19ad470a7b4410e65ca5f1008e38fc923f985d17ff7752"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.432.0/speakeasy_linux_amd64.zip"
        sha256 "ea628f03efa3880efed2f39617463ccfc8e2799416e67c3744edf19340ceb96f"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.432.0/speakeasy_linux_arm64.zip"
        sha256 "a9e474bfe22938802436f1acc08029d216bf1cf8bafa0154e9acf076ae1f327f"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
