# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12013 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.201.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.201.3/speakeasy_darwin_arm64.zip"
      sha256 "f67b609ff950d1d7563017c862d170fb0ede316e7477ee39c733597c6d4857fe"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.201.3/speakeasy_darwin_amd64.zip"
      sha256 "fa8ccecea234598745c6d7755b3617754abbcc767bc43e77b53511a5b08c7e8f"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.201.3/speakeasy_linux_arm64.zip"
      sha256 "bf9d77e7127ef078b3280164b915c7bd18127bf03725e466eb9169a2f8257a3a"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.201.3/speakeasy_linux_amd64.zip"
      sha256 "3ca66c97fef6f44bdfd8027e3356e434417869cfee53b3e32c6f4e376174cd36"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
