# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14103 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.410.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.410.3/speakeasy_darwin_amd64.zip"
      sha256 "e1ae584ed0e3ef41b24cadbfb9366d93c8784dbb4513b1a2d14045b2d7714cc3"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.410.3/speakeasy_darwin_arm64.zip"
      sha256 "36ad85c082f8833b69c402f620bc5340429ffe2cf50661ca4a364b7cf382915f"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.410.3/speakeasy_linux_amd64.zip"
        sha256 "9180307e534ade1ba8aeac67d1ce747ce024bd0925e8bce6b4d6a803197503c7"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.410.3/speakeasy_linux_arm64.zip"
        sha256 "31e85498182d13561ee568bf2363ddda947768497cfa43c91386a79a31cab51d"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
