# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14689 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.468.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.468.9/speakeasy_darwin_amd64.zip"
      sha256 "467b3ec0b19ee0ff7b90ffc85f13991897ddf90d41e1c3f45a2806090cebfb75"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.468.9/speakeasy_darwin_arm64.zip"
      sha256 "d2b8209fc032235b1e43740de3b4d87a7ec7fd920ae5ea43ad60b9bf46ee1120"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.468.9/speakeasy_linux_amd64.zip"
        sha256 "d03ff48deb5458f568ea033c6ba64e0cc9e58b8771dfef119fb9715f5555511a"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.468.9/speakeasy_linux_arm64.zip"
        sha256 "4e6f287189fea0dda0aac2654d15c44da3cdca4cc2c0fd507379b46f22722967"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
