# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11901 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.190.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.190.1/speakeasy_darwin_arm64.zip"
      sha256 "afbafd3b9581a045c5ba5a92d6a9f968e1e432612b140993215ab4afe4234204"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.190.1/speakeasy_darwin_amd64.zip"
      sha256 "52fe6b57497af5d262cb5700df1126ad0680afccd5c6a2adfe866b01e10b2e20"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.190.1/speakeasy_linux_arm64.zip"
      sha256 "461306c31188e80d67590145d3af17d9a926f161de0e14fa2e38a664142dc915"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.190.1/speakeasy_linux_amd64.zip"
      sha256 "57731370d015dab3511ac6beee695a8b1d5c5a9a21f3dbe285f7e939bb2da164"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
