# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14700 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.470.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.470.0/speakeasy_darwin_amd64.zip"
      sha256 "27d87797b8cb9e4c80a171f115f34bd1d1b0f9c3f1f0b10e6dfd53f957312b2e"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.470.0/speakeasy_darwin_arm64.zip"
      sha256 "e538c7c815ac4c6668f1153ea8dded83d6e6ee6c531ae81b570bf31429ffa453"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.470.0/speakeasy_linux_amd64.zip"
        sha256 "ffc4c78f30b062b55d6ec86a32637a91dd386e2c7d1c1490b25e1d552ebf9a7c"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.470.0/speakeasy_linux_arm64.zip"
        sha256 "91ae79c338a6fe723c82b6fdb77c3157565a46b89bddcfabe4b10dcd8aa5a6d3"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
