# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1301 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.30.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.30.1/speakeasy_1.30.1_Darwin_arm64.tar.gz"
      sha256 "07b43669300be68704292d17d6c087aba0664d36f767cce5fab4980e2b8db253"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.30.1/speakeasy_1.30.1_Darwin_x86_64.tar.gz"
      sha256 "42b7ad57444da09a7c1d6c9425de2f8a25181e3eb89d307ba2aac6e8d44a5478"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.30.1/speakeasy_1.30.1_Linux_x86_64.tar.gz"
      sha256 "184568db49d3b959eb6a50b18879ec622dc6effca6a1ec2fbe7ea6df65725434"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.30.1/speakeasy_1.30.1_Linux_arm64.tar.gz"
      sha256 "059236b4ba9750446be627f2c7e21ea3a35c473f71c6cca67dd49ca3a950aede"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
