# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1142 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.14.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.14.2/speakeasy_1.14.2_Darwin_arm64.tar.gz"
      sha256 "a2be14516678ea743a63cafe69e42d22c539e7dec44d9b861ce4f1acdafdbea5"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.14.2/speakeasy_1.14.2_Darwin_x86_64.tar.gz"
      sha256 "6a9880ed4399e74c918ccfc9f0f15c54fe39459a8417abbc1f3fe3a27c283cc6"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.14.2/speakeasy_1.14.2_Linux_arm64.tar.gz"
      sha256 "e78da8a48d8e07e9130e6dd3fa1d4390a3cc2691f4a99c6388e880c2cabca733"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.14.2/speakeasy_1.14.2_Linux_x86_64.tar.gz"
      sha256 "b024ae6a9205195f4c0b7a5bbc3b8d0909308fff855bb6acfb5c81e98d0674e5"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
