# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13660 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.366.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.366.0/speakeasy_darwin_amd64.zip"
      sha256 "e4893a3944a49b970fcd58d721b880db00d679db1c60690a8af7a41f72836241"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.366.0/speakeasy_darwin_arm64.zip"
      sha256 "8bd466c4972e1126ee00399227b2fdd4de903a56af868ef23cc7ab00bd9d12d3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.366.0/speakeasy_linux_amd64.zip"
        sha256 "1d32be904302c1ee0b3f9e83ee48f056283123a927a57344eca6a922a0b62cf9"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.366.0/speakeasy_linux_arm64.zip"
        sha256 "07e7af5a2c3fdbc0b88f136c836388332cee7ae76ba8d8264421769e25242e56"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
