# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12610 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.261.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.261.0/speakeasy_darwin_amd64.zip"
      sha256 "0a0d00d0ad0ec03e440a14199d0a00a28022174085955bcc0b886e6ca4c7fc69"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.261.0/speakeasy_darwin_arm64.zip"
      sha256 "4b6e3a82a74817fb50ffb9a20de2014bda5db14024cca212ac00e9af84d77063"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.261.0/speakeasy_linux_amd64.zip"
      sha256 "f423196f04929e397780da90f6d2e6d8d203a576badb869b4db912c5e3e399aa"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.261.0/speakeasy_linux_arm64.zip"
      sha256 "9bc618d5af5628c12823a4298943aafb7860244e52b1ee6b9999c56b9e0e7455"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
