# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14033 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.403.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.403.3/speakeasy_darwin_amd64.zip"
      sha256 "e979fc7ca7448857eedf123778081073ba6d2cd5cb0b455a618af4400755841e"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.403.3/speakeasy_darwin_arm64.zip"
      sha256 "1c3752e04c3f2c7c3978d025f897b1f1c28f95f1483d1fc55929748a65b39c62"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.403.3/speakeasy_linux_amd64.zip"
        sha256 "1991c0bba522c620bad6f2374e5abc4d961e683f29e4136c4b746356a06a35b5"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.403.3/speakeasy_linux_arm64.zip"
        sha256 "714f799a073c32a6e25633c3ee73c8509d4f1cc0d6d7c1970731eff30bb7b68c"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
