# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12400 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.240.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.240.0/speakeasy_darwin_amd64.zip"
      sha256 "64c7a1ea7e57154c43f03ec246f3a3c99afcabb6af9d395e898d48b4f913d0c5"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.240.0/speakeasy_darwin_arm64.zip"
      sha256 "c2b92eaaf037f27c2dd38b916e97887fcd351a1d4bba3997424c511e1881b93e"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.240.0/speakeasy_linux_amd64.zip"
      sha256 "22be92f1ecdfc4ef7389f08dc754d7e8177aab51f2b8483f99eb3257aee0d5f2"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.240.0/speakeasy_linux_arm64.zip"
      sha256 "ec7f2504a0740387aa973d34ad757813035febcb689d29b8d5b71dffa26c4e3d"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
