# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13832 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.383.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.383.2/speakeasy_darwin_amd64.zip"
      sha256 "8c6d194a4d355bd5ed450526e3ad21936f4762201de53f3367cda63695be2044"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.383.2/speakeasy_darwin_arm64.zip"
      sha256 "8433d53bf2eecc9d3bf3191837b71201aae2dacbf781e9c9e8e4917b05d4fd46"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.383.2/speakeasy_linux_amd64.zip"
        sha256 "b25daa2342621b33b5d3a1c77e84c70ca815d8ba6d0a668b96b85293e0bcf1be"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.383.2/speakeasy_linux_arm64.zip"
        sha256 "69de1356f0dfd44165a4976b6cedc56c27a4d98d735ad0b72b60fd3f4a7a8ebb"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
