# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1830 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.83.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.83.0/speakeasy_darwin_arm64.zip"
      sha256 "abc566006c71dca1badf1f5d4fa689192e848601f3b5dfd4f56a20f4fa02f3c5"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.83.0/speakeasy_darwin_amd64.zip"
      sha256 "55f8999dde1e0f94e2973e923ad4dd866a0e8cdd8709bea48702540e33ee8b57"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.83.0/speakeasy_linux_amd64.zip"
      sha256 "daf9cf67c1b68309694f50435db868bdae862626b6dbc8bd67a9ff65c19d0225"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.83.0/speakeasy_linux_arm64.zip"
      sha256 "6576aa3461a0a682d4122a56c2f8cabb9bea715efb8c629e0c4b8a7470f2dcd6"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
