# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13790 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.379.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.379.0/speakeasy_darwin_amd64.zip"
      sha256 "552a29c49b8a6e276349baf17984a479d53451d09c1428b8810f32de5ff029fb"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.379.0/speakeasy_darwin_arm64.zip"
      sha256 "4f05e7446efa72910e90983bb58a82a75b8e3ad17340a6667108187bbc270181"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.379.0/speakeasy_linux_amd64.zip"
        sha256 "4e6c3d1780c4bfbe752267af8f2d9aae58afe9f4e1cc589c77272f2d650aec80"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.379.0/speakeasy_linux_arm64.zip"
        sha256 "4d84e3cf47d2be6dd7c01f1f3d2c87d3fa9e236247e551a6b94973c7c8b34f99"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
