# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11213 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.121.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.121.3/speakeasy_darwin_arm64.zip"
      sha256 "f723995c4dcea36efc889980a05993ccfddc2a453a67cf4bb03115078fe1a27a"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.121.3/speakeasy_darwin_amd64.zip"
      sha256 "dc36c71e424fb1059bc6bd27acb7bf4a42eca952c6b5bd5ffdf630604c672064"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.121.3/speakeasy_linux_amd64.zip"
      sha256 "e501d6c1a49c1f1c83fd8788699cf2b4a29a6c7de7ec96574001b34f952e7a03"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.121.3/speakeasy_linux_arm64.zip"
      sha256 "8af3a6adcbdfb8dbfeb10718cf7e9e4f4643c0cddc8dea467ae1c0c758dc16e3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
