# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13912 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.391.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.391.2/speakeasy_darwin_amd64.zip"
      sha256 "c9a94141607f25f73a3d5b7b4ea01d69f04758c4cf77d9c58499242216ba9d0f"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.391.2/speakeasy_darwin_arm64.zip"
      sha256 "6afa798088632952b625f2022164feba01d0f75252fb2ba9ccb937b99de48b1b"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.391.2/speakeasy_linux_amd64.zip"
        sha256 "6a7795cb47a03bbcc60a81bf24ce62c29aa29ab5c6dd2f4b3dde28d9ad51a194"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.391.2/speakeasy_linux_arm64.zip"
        sha256 "a3f1c68b2ddcd2e9c0e4088a124ea1ceb583186711598f466bb2a4bea4fd5e6b"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
