# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1740 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.74.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.74.0/speakeasy_darwin_arm64.zip"
      sha256 "72b63b530638b2ed553ad1f2be18ae6085d55371eb705233738ddb510c65856c"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.74.0/speakeasy_darwin_amd64.zip"
      sha256 "2faf139e522c59bd4e33079d129bc008e73fb9b63f510327291c23df8247338f"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.74.0/speakeasy_linux_arm64.zip"
      sha256 "5feaf0386b2999d553d8e3093c4f5ad2f862e5674a31cf3661573265a3713334"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.74.0/speakeasy_linux_amd64.zip"
      sha256 "bdcaa69794c353387fe9400cb415e1a697565664c449cb416c5a9101c353a30c"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
