# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12670 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.267.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.267.0/speakeasy_darwin_amd64.zip"
      sha256 "a31599a671991f600743833c764f8ca75d922a31f96a79a25345e1a6c2e8548e"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.267.0/speakeasy_darwin_arm64.zip"
      sha256 "b7ba58e99c8be4cd35f59587c93af73e58c75883cd8bc3b95786b4fd42e27986"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.267.0/speakeasy_linux_amd64.zip"
      sha256 "4a2874abc0ca1b02f36b501cc74a44cb73bc4c12178d19fc90a74523e2eb3dbb"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.267.0/speakeasy_linux_arm64.zip"
      sha256 "b18211c32a2ab3ba8a4b13b6f4e491387d58a220e2a46377f1171bf2a1dc2092"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
