# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14213 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.421.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.421.3/speakeasy_darwin_amd64.zip"
      sha256 "b20e4a2d7eaa928c8bb5ca21b65b54b12d931b2a7477beb2bb06f24dd1b1db21"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.421.3/speakeasy_darwin_arm64.zip"
      sha256 "20c5cef8b428bbd7090272ba56cdf2fc6b91b00cc3b28dbae899ec970990ca0a"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.421.3/speakeasy_linux_amd64.zip"
        sha256 "d2d1d4b45e34a50f9a41d7f6d5138ac12faa8a338d765e4023c52c15a270a22d"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.421.3/speakeasy_linux_arm64.zip"
        sha256 "653f9c51a0dd09e91e0ea11d92eae0c98fbb16da90e806aa897c009317c8587e"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
