# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11951 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.195.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.195.1/speakeasy_darwin_arm64.zip"
      sha256 "c8196f42d2a4539215167d4a709446905f832f54dc9bcf0a4bc904ae58b71025"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.195.1/speakeasy_darwin_amd64.zip"
      sha256 "62bd78cea4224b8d2c5744c5856f0c33a63819316d4e9cf247741d6e7763868d"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.195.1/speakeasy_linux_arm64.zip"
      sha256 "326872fc5086ea930126c2c74d1253e119daeb7de298aa6ed87c4c2419b9d4bf"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.195.1/speakeasy_linux_amd64.zip"
      sha256 "d88cceb8721a269e46c538d3d75a72a46fe4fc232f28111a16b5649aee097421"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
