# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15280 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.528.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.528.0/speakeasy_darwin_amd64.zip"
      sha256 "615619d5aede33d766879c305a31541c20d203514ab2935f88c45647ffda77ca"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.528.0/speakeasy_darwin_arm64.zip"
      sha256 "fdf16a3063d9fe091cdc36a83f20850646a4a0da13b2f94ae0a060b404cf8e44"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.528.0/speakeasy_linux_amd64.zip"
        sha256 "f79556cb90cf1009316e07f5a08ec3c48e68d038500604eb8b634db06f3b1307"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.528.0/speakeasy_linux_arm64.zip"
        sha256 "9cf43cc7967b8fe9f006c4911c9f00ce0433ec09b9a4e6f0bfc96f7e1ef46a0a"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
