# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14880 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.488.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.488.0/speakeasy_darwin_amd64.zip"
      sha256 "75cdd18a59dfd75f6f52bee5aba7748ac9af6c0cb640bf647a60d2a19a4b18dd"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.488.0/speakeasy_darwin_arm64.zip"
      sha256 "b11231ea974437d97ba7b40c12b7f040f948e72925029ca68bceaf23c2afc1ec"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.488.0/speakeasy_linux_amd64.zip"
        sha256 "7fa8c3b39fe3b703c766520defb38bc006f130165bf7852cd9e04074efab7391"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.488.0/speakeasy_linux_arm64.zip"
        sha256 "3897858fd71ee8f8e1b0a71b3fa6740bc7880eb50e19fc002859747fec0ddacf"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
