# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14670 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.467.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.467.0/speakeasy_darwin_amd64.zip"
      sha256 "67025b318a0ecd0e2ca6cbe22227607df6093eebccb1fd3af3c7a07e2d63cebf"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.467.0/speakeasy_darwin_arm64.zip"
      sha256 "aae214a3226dbbfc75d228647d02bb88b9298bd36565e86453649c2ba949a8b3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.467.0/speakeasy_linux_amd64.zip"
        sha256 "b2823206c28a42c6dd21482c26a564ddaebe5f21825a5bc8368d1c5676f651ea"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.467.0/speakeasy_linux_arm64.zip"
        sha256 "f2d0f3e9c955c889a0166f003a4c51e7bd2aee164a2f727bf87ba3d07e28b3ca"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
