# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyHooks < Formula
  desc "Speakeasy observability hooks for coding agents"
  homepage "https://app.getgram.ai"
  version "0.3.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.15/speakeasy-hooks_darwin_amd64.zip"
      sha256 "345ac746f3d5f4800cf74d3dc3f0c2ef3760639097e567b92d1bccb54f6a58ec"

      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.15/speakeasy-hooks_darwin_arm64.zip"
      sha256 "7d7e6db29cdf9f8e2498af0d04a7c99787a9b39560dfed31d87cffb866bc17d3"

      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.15/speakeasy-hooks_linux_amd64.zip"
      sha256 "4ed29dcdbd6b773467a52a989ebfebb8f337d67f6d704969282256b8d0c77d2e"
      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/gram/releases/download/hooks@0.3.15/speakeasy-hooks_linux_arm64.zip"
      sha256 "e7f94b2634740dda9d45aa7dd8cf7c7571ffd2e1fe84aab583116d262660a08c"
      define_method(:install) do
        bin.install "speakeasy-hooks"
      end
    end
  end

  test do
    system "#{bin}/speakeasy-hooks --version"
  end
end
