# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13020 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.302.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.302.0/speakeasy_darwin_amd64.zip"
      sha256 "4577a27e60030a41db65a93395d336ae9190d0f679c467fc0a5da2174d6a964f"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.302.0/speakeasy_darwin_arm64.zip"
      sha256 "3337deb6eface0c63fdc4f47ed008b8afb5e5106ca69bdaf9b83b164475f98b1"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.302.0/speakeasy_linux_amd64.zip"
        sha256 "862d8c245ab90c15ee7a0584783ffdeac401ed966c40ad471b1cae244c374f2a"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.302.0/speakeasy_linux_arm64.zip"
        sha256 "7199d455f410b4b3b26748716f81cc9d9378eb2564dc16def62ec4a490c94fc1"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
