# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT11940 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.194.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.194.0/speakeasy_darwin_arm64.zip"
      sha256 "08faf073282df272f4606f22c019ac397f78d39b740d6f1de000b139f279443c"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.194.0/speakeasy_darwin_amd64.zip"
      sha256 "2cb3e8db20d0fec15095a92cdc9162129fcee4ae2bf445c07e4f05003ab8037b"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.194.0/speakeasy_linux_arm64.zip"
      sha256 "eb13ae75a3f3aa64cf3245904c15ea1f31f859bf8df52165b100291ed9897153"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.194.0/speakeasy_linux_amd64.zip"
      sha256 "2bfd74d451ca41cbe91988c497ece3c4d9a0f32e4bc75d71482ed6d01e49763b"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
