# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT13940 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.394.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.394.0/speakeasy_darwin_amd64.zip"
      sha256 "715a4173d1a96261280dd08a5e68b43ab4cab7f6ded2823e132830a8b60363b5"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.394.0/speakeasy_darwin_arm64.zip"
      sha256 "ab7874c70503ea6a9f0c7a12f22fce066be28ccc3373667be2bda034edc712a3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.394.0/speakeasy_linux_amd64.zip"
        sha256 "bd938494f8e4c72c632ff6c85babf89918ec4809738dc45ab0778bf1fb9931a9"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.394.0/speakeasy_linux_arm64.zip"
        sha256 "c203b3cb625e1485492f511d3e96709b4dd1952933b47402e7905f075df3cdd3"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
