# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15392 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.539.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.539.2/speakeasy_darwin_amd64.zip"
      sha256 "5e3c94aa2f01be4befc005915339d03cb3b2bae401abcaf6b57e06107c3bcdd4"

      def install
        bin.install "speakeasy"
        bash_completion.install "completions/speakeasy.bash" => "speakeasy"
        zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
        fish_completion.install "completions/speakeasy.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.539.2/speakeasy_darwin_arm64.zip"
      sha256 "72ed3d9d3eb9caf5a5f29a67eded1ff04d75358250080a76764f2b29942997f0"

      def install
        bin.install "speakeasy"
        bash_completion.install "completions/speakeasy.bash" => "speakeasy"
        zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
        fish_completion.install "completions/speakeasy.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.539.2/speakeasy_linux_amd64.zip"
        sha256 "91399776a604a6e98eba7e8edfeef5c9a620946d7d1e4f01be3707bf17fedcf6"

        def install
          bin.install "speakeasy"
          bash_completion.install "completions/speakeasy.bash" => "speakeasy"
          zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
          fish_completion.install "completions/speakeasy.fish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.539.2/speakeasy_linux_arm64.zip"
        sha256 "c353c13a3d47240b9b882c149ab6b26c5e1532317207888ce26467466e780f9b"

        def install
          bin.install "speakeasy"
          bash_completion.install "completions/speakeasy.bash" => "speakeasy"
          zsh_completion.install "completions/speakeasy.zsh" => "_speakeasy"
          fish_completion.install "completions/speakeasy.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
