# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1760 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.76.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.76.0/speakeasy_darwin_amd64.zip"
      sha256 "5d5e9116ed08d359efa29baafc26485de627183dbf413354155b23a1d349bd51"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.76.0/speakeasy_darwin_arm64.zip"
      sha256 "20d7025b94128ecd506b7ac64d2daf9cbb3cbb23603f3da48ae6d8960f61bf19"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.76.0/speakeasy_linux_arm64.zip"
      sha256 "f01ddf7e1ef1fae1981a02eeedf79e64900c942df3f24029fe0e95cb976268ef"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.76.0/speakeasy_linux_amd64.zip"
      sha256 "f5f0e84b6c907e4295101ea37a658d39f0fcf14ee3f14771417ea8c5ef0888bc"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
