# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT12230 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.223.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.223.0/speakeasy_darwin_arm64.zip"
      sha256 "c180be15b5b92029509e3d8f35008e8fc132d2591610e69b262365c99d629699"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.223.0/speakeasy_darwin_amd64.zip"
      sha256 "0ebb587ad25c0683a5496946004ac51d58f911f77d87f0e718e67822b249e524"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.223.0/speakeasy_linux_arm64.zip"
      sha256 "148b15aee5a97d71cfa322b40c2ca836aaa78267bd966508319bcd9d79cd9d23"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.223.0/speakeasy_linux_amd64.zip"
      sha256 "de9621a29e91470737f6bb367f098a1231db6e473967a790140ae70ec10b8167"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
