# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1452 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.45.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.45.2/speakeasy_darwin_arm64.zip"
      sha256 "a4bf8a34dd2cdab8e050f8173482921d9386587df8027a1cb777637026766618"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.45.2/speakeasy_darwin_amd64.zip"
      sha256 "c9188a83fc87807eac5ee53a183bc64faebefdb218431ca4225fdb69a7ee48c3"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.45.2/speakeasy_linux_arm64.zip"
      sha256 "aaf815762541528b92097e8893227c3cd0e47d92c7ac7485ce324f962affa118"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.45.2/speakeasy_linux_amd64.zip"
      sha256 "59dbb70908c3f2d0df4605ce9a8348da251f0e1ba1282d0e49c03ea670e2cb5c"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
