# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT15265 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.526.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.526.5/speakeasy_darwin_amd64.zip"
      sha256 "ab80500cd5a4b197351afbf21744f723d99deee52ec7e0a44f49a23cc53eb796"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.526.5/speakeasy_darwin_arm64.zip"
      sha256 "107e2fe516c48a1d3ab2b848df7bd6ac8e7656788b77fd7c60ca61cdec32eb34"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.526.5/speakeasy_linux_amd64.zip"
        sha256 "1f1030f8f39ebbd791e03780385ae9ba5180221e1bb706e560abaed91dd293de"

        def install
          bin.install "speakeasy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.526.5/speakeasy_linux_arm64.zip"
        sha256 "937ffd2239a21eb0a9735f67f0c7be1dc8c93f0ce2f99351a1d613e8af6a411a"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
