# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT1786 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasyapi.dev"
  version "1.78.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.6/speakeasy_darwin_amd64.zip"
      sha256 "cb708cfb54381cf687bce95235b136854e0bc6ca1b98f402e820f6a17ef958bc"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.6/speakeasy_darwin_arm64.zip"
      sha256 "e067c43df15f0eb33f9c33f98ca86044a4906c8fada805b7da95efce1fa6d4b5"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.6/speakeasy_linux_amd64.zip"
      sha256 "9f5e2487cf71d0df0bcbeb305fe00e9bc5a858a4988b8a160086f9b44fc34c7f"

      def install
        bin.install "speakeasy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.78.6/speakeasy_linux_arm64.zip"
      sha256 "f0b17e3120f6c5926a5d1773d0ebe0f228be4e9656d2e5f9f7e536bf5b750574"

      def install
        bin.install "speakeasy"
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
