# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpeakeasyAT14473 < Formula
  desc "The Speakeasy CLI for interacting with the Speakeasy Platform"
  homepage "https://www.speakeasy.com"
  version "1.447.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.447.3/speakeasy_darwin_amd64.zip"
      sha256 "f7fe5dab18c64a65e1a85a7f90f2c562d0d10657ef41fc90f6a840223e185bca"

      def install
        bin.install "speakeasy"
      end
    end
    on_arm do
      url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.447.3/speakeasy_darwin_arm64.zip"
      sha256 "43902a39d51af8e0ca1f201c505c1fc33034b8c2e0dbe24c35217cb2608f47b6"

      def install
        bin.install "speakeasy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.447.3/speakeasy_linux_amd64.zip"
        sha256 "dbd8e7560a1608dbd3af04d760a0cff289f058eae02bd3318965afbbcf6fdf5b"

        def install
          bin.install "speakeasy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/speakeasy-api/speakeasy/releases/download/v1.447.3/speakeasy_linux_arm64.zip"
        sha256 "53921966c7f81d72c493d7cc80ad80945930917893468420acf502ca0621681a"

        def install
          bin.install "speakeasy"
        end
      end
    end
  end

  test do
    system "#{bin}/speakeasy --version"
  end
end
